#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Regenerate docs/site/user-guide.html from docs/user-guide/**.md
#
#   ./tools/build-user-guide/build-user-guide.sh              # build with the detected runtime
#   ./tools/build-user-guide/build-user-guide.sh --check      # CI: fail if the HTML is stale
#   ./tools/build-user-guide/build-user-guide.sh --record     # record the current state as built
#   ./tools/build-user-guide/build-user-guide.sh --runtime claude
#   ./tools/build-user-guide/build-user-guide.sh --dry-run    # print the invocation only
#
# The guide is authored, not compiled: the build step is an agent run driven by
# BUILD_USER_GUIDE_PROMPT.md. --check is pure bash and needs no runtime, so it is
# safe to gate every pull request on it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SRC_DIR="$REPO_ROOT/docs/user-guide"
OUT_DIR="$REPO_ROOT/docs/site"
OUT_HTML="$OUT_DIR/user-guide.html"
MANIFEST="$OUT_DIR/.user-guide.manifest"
PROMPT="$SCRIPT_DIR/BUILD_USER_GUIDE_PROMPT.md"

MODE="build"
RUNTIME="${KONDUCTOR_GUIDE_RUNTIME:-auto}"
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --check)    MODE="check" ;;
    --record)   MODE="record" ;;
    --runtime)  RUNTIME="${2:?--runtime needs a value: kiro|claude}"; shift ;;
    --dry-run)  DRY_RUN=1 ;;
    -h|--help)  sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)          echo "unknown argument: $1" >&2; exit 64 ;;
  esac
  shift
done

die() { echo "error: $*" >&2; exit 1; }

[ -d "$SRC_DIR" ] || die "no $SRC_DIR — run this from inside the repository"
[ -f "$PROMPT" ]  || die "missing prompt: $PROMPT"

# Resolve the hashing tool once, as an argv array: xargs execs a real command,
# so a shell function cannot be used here.
if command -v sha256sum >/dev/null 2>&1; then
  SHA=(sha256sum)
else
  SHA=(shasum -a 256)
fi

sha_cmd() { "${SHA[@]}"; }

# Content hash of every Markdown file in the guide, path-sorted so it is stable.
#
# The emptiness check is not paranoia: given no paths, GNU xargs still runs the
# hashing tool once, which then hashes stdin (/dev/null) and yields a plausible,
# stable digest for an empty guide. `[ -d "$SRC_DIR" ]` alone would let that
# through. Checked with a separate find rather than `xargs -r`, which older BSD
# xargs does not have, and not by capturing -print0 output in a variable, since
# command substitution strips the NULs this pipeline depends on.
content_hash() {
  if [ -z "$(find "$SRC_DIR" -name '*.md' -type f -print -quit)" ]; then
    die "no .md files under $SRC_DIR"
  fi
  find "$SRC_DIR" -name '*.md' -type f -print0 \
    | LC_ALL=C sort -z \
    | xargs -0 "${SHA[@]}" \
    | sed "s|$REPO_ROOT/||" \
    | "${SHA[@]}" \
    | cut -d' ' -f1
}

CURRENT_HASH="$(content_hash)"

write_manifest() {
  {
    echo "# Generated by tools/build-user-guide/build-user-guide.sh — do not edit."
    echo "content_sha256=$CURRENT_HASH"
    echo "built_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "runtime=$1"
    echo "source_commit=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "output_sha256=$(sha_cmd < "$OUT_HTML" | cut -d' ' -f1)"
  } > "$MANIFEST"
}

# --record: the HTML was updated by the deterministic tools
# (tools/user-guide-sync/apply-renames.py and
# tools/build-user-guide/sync-html-content.py) rather than by an agent run.
# Record the current pair as built so --check has a baseline.
if [ "$MODE" = "record" ]; then
  [ -f "$OUT_HTML" ] || die "$OUT_HTML does not exist — nothing to record"
  mkdir -p "$OUT_DIR"
  write_manifest "deterministic"
  echo "recorded: $MANIFEST ($CURRENT_HASH)"
  exit 0
fi

if [ "$MODE" = "check" ]; then
  [ -f "$OUT_HTML" ] || die "$OUT_HTML does not exist — run this script without --check"
  [ -f "$MANIFEST" ] || die "$MANIFEST does not exist — run this script without --check"
  RECORDED_HASH="$(grep '^content_sha256=' "$MANIFEST" | cut -d= -f2)"
  if [ "$CURRENT_HASH" != "$RECORDED_HASH" ]; then
    cat >&2 <<EOF
error: docs/site/user-guide.html is out of date.

  docs/user-guide/ content hash : $CURRENT_HASH
  hash recorded at last build   : $RECORDED_HASH

Regenerate it and commit the result:

  ./tools/build-user-guide/build-user-guide.sh
EOF
    exit 1
  fi

  # The Markdown hash alone leaves the other half of the pair unguarded: a bundle
  # that was hand-edited, truncated, or patched by one of the sync tools without a
  # re-record still passes a content-only check, because docs/user-guide/**.md
  # never moved. Re-hash the bundle against what --record pinned.
  RECORDED_OUTPUT_HASH="$(grep '^output_sha256=' "$MANIFEST" | cut -d= -f2)"
  if [ -z "$RECORDED_OUTPUT_HASH" ]; then
    die "$MANIFEST has no output_sha256 — re-record it with --record"
  fi
  CURRENT_OUTPUT_HASH="$(sha_cmd < "$OUT_HTML" | cut -d' ' -f1)"
  if [ "$CURRENT_OUTPUT_HASH" != "$RECORDED_OUTPUT_HASH" ]; then
    cat >&2 <<EOF
error: docs/site/user-guide.html has changed since the last build.

  current bundle hash         : $CURRENT_OUTPUT_HASH
  hash recorded at last build : $RECORDED_OUTPUT_HASH

The Markdown is unchanged, so the bundle was edited on its own. Re-run the sync
tools and record the result:

  make guide
EOF
    exit 1
  fi

  echo "ok: user-guide.html matches docs/user-guide/ ($CURRENT_HASH)"
  echo "ok: bundle matches what was recorded ($CURRENT_OUTPUT_HASH)"
  exit 0
fi

# ---- build -------------------------------------------------------------------

if [ "$RUNTIME" = "auto" ]; then
  if   command -v kiro-cli >/dev/null 2>&1; then RUNTIME="kiro"
  elif command -v claude   >/dev/null 2>&1; then RUNTIME="claude"
  else die "no AI runtime found — install kiro-cli or claude, or pass --runtime"
  fi
fi

mkdir -p "$OUT_DIR"

REQUEST="Regenerate the HTML user guide by following, exactly, the instructions in \
$PROMPT (read that file first). Source of truth: $SRC_DIR. Output: $OUT_HTML. \
Also write $OUT_DIR/USER_GUIDE_BUILD_NOTES.md. Do not edit any file under $SRC_DIR."

case "$RUNTIME" in
  kiro)   CMD=(kiro-cli chat --agent konductor --no-interactive "$REQUEST") ;;
  claude) CMD=(claude --agent konductor -p "$REQUEST") ;;
  *)      die "unknown runtime '$RUNTIME' (expected kiro or claude)" ;;
esac

echo "runtime : $RUNTIME"
echo "source  : $SRC_DIR"
echo "output  : $OUT_HTML"
echo "hash    : $CURRENT_HASH"

if [ "$DRY_RUN" = "1" ]; then
  printf 'would run:'; printf ' %q' "${CMD[@]}"; printf '\n'
  exit 0
fi

BEFORE_HASH=""
[ -f "$OUT_HTML" ] && BEFORE_HASH="$(sha_cmd < "$OUT_HTML" | cut -d' ' -f1)"

"${CMD[@]}"

[ -f "$OUT_HTML" ] || die "the run finished but $OUT_HTML was not written"
[ -s "$OUT_HTML" ] || die "$OUT_HTML is empty"

# Cheap post-conditions — catch the failure modes that matter without opening a browser.
grep -qi 'konductor' "$OUT_HTML" || die "$OUT_HTML has no Konductor content"
if grep -qiE 'flowchart (TD|LR)|```mermaid' "$OUT_HTML"; then
  die "$OUT_HTML contains raw Mermaid source — diagrams must be hand-built HTML"
fi
for token in TODO FIXME lorem; do
  if grep -qi "$token" "$OUT_HTML"; then
    echo "warning: '$token' appears in the output — check the build notes" >&2
  fi
done

# The conditions above all read characters, which is exactly what a broken bundle
# still gets right. The page boots by handing its `data-dc-script` block to
# `new Function()`, so a single unescaped `"` spliced in from prose closes a JS
# string literal early, the eval aborts, and the reader gets a blank page with
# nothing but a SyntaxError in a console they will never open. The block sits
# inside the escaped `__bundler/template` string, so it cannot be checked against
# this file directly — check-bundle-js.py decodes the page first, then parses.
python3 "$SCRIPT_DIR/check-bundle-js.py" "$OUT_HTML" \
  || die "$OUT_HTML ships JavaScript that does not parse — the page would render blank"

write_manifest "$RUNTIME"

AFTER_HASH="$(sha_cmd < "$OUT_HTML" | cut -d' ' -f1)"
if [ "$BEFORE_HASH" = "$AFTER_HASH" ]; then
  echo "note: output is byte-identical to the previous build"
fi

echo "built: $OUT_HTML"
echo "manifest: $MANIFEST"
